=== MaxEtMoritz/openMensaMax/canteens.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "p": {
                "type": "string",
                "description": "MensaMax project (\"Projekt\") for this canteen.",
                "examples": ["N111"]
            },
            "e": {
                "type": "string",
                "description": "MensaMax institution (\"Einrichtung\") for this canteen.",
                "examples": ["Mensa"]
            },
            "provider": {
                "type": "string",
                "description": "MensaMax provider this canteen is on (MensaMax has some distinct systems under different URLs).",
                "examples": [
                    "mensadigital.de",
                    "mensaservice.de",
                    "mensaonline.de",
                    "mensapoint.de",
                    "mensahome.de",
                    "mensaland.de",
                    "mensaweb.de",
                    "mensawelten.de",
                    "mensacity.de",
                    "mensaoffice.de",
                    "mammasmensa.de",
                    "mensalokal.de",
                    "mensastadt.de",
                    "mensahaus.de",
                    "parentsmensa.de",
                    "mensaaktiv.de",
                    "mensacenter.de",
                    "app.mensamax.de"
                ],
                "not": {
                    "type": "string",
                    "description": "This MensaMax provider is unsupported.",
                    "pattern": "^mensa365.de$"
                }
            },
            "name": {
                "type": "string",
                "description": "Human-readable name for the canteen (optional)."
            },
            "$comment": {
                "type": "string",
                "description": "Any notes for this canteen."
            },
            "om_id":{
                "type": "integer",
                "description": "ID of the canteen in OpenMensa if already created there."
            },
            "loc":{
                "type": "string",
                "description": "Location of the canteen (e.g. name of city/village/...)"
            }
        },
        "required": ["p", "e", "provider"],
        "additionalProperties": false
    },
    "additionalItems": false,
    "uniqueItems": true
}

=== MaxEtMoritz/openMensaMax/pages/_data/canteens.json
[
    {
        "provider": "mensaservice.de",
        "p": "N111",
        "e": "Mensa",
        "name": "Wilhelm-Löhe-Schule Nürnberg",
        "loc": "Nürnberg",
        "om_id": 1799
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "dts",
        "name": "Dr.-Theo-Schöller-Mittelschule in Nürnberg",
        "loc": "Nürnberg",
        "om_id": 1800
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "ghr",
        "name": "Georg-Hartmann-Realschule Forchheim",
        "loc": "Forchheim",
        "om_id": 1802
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "hoch",
        "name": "Gymnasium Höchstadt a.d.Aisch",
        "loc": "Höchstadt a.d.Aisch",
        "om_id": 1803
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "herz",
        "name": "Gymnasium Herzogenaurach",
        "loc": "Herzogenaurach",
        "om_id": 1804
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "mscadolzburg",
        "name": "Mittelschule Cadolzburg",
        "loc": "Cadolzburg",
        "om_id": 1805
    },
    {
        "provider": "mensadigital.de",
        "p": "HH2306",
        "e": "Irena-Sendler",
        "name": "Irena-Sendler-Schule",
        "loc": "Hamburg",
        "om_id": 1806
    },
    {
        "provider": "mensadigital.de",
        "p": "HH2306",
        "e": "GS-Hegholt",
        "name": "Grundschule Bramfeld",
        "loc": "Hamburg",
        "om_id": 1807
    },
    {
        "provider": "mensadigital.de",
        "p": "HP2329",
        "e": "Goethe",
        "name": "Goethe-Gymnasium Bensheim",
        "loc": "Bensheim",
        "om_id": 1808
    },
    {
        "provider": "mensadigital.de",
        "p": "HP2329",
        "e": "Gutenberg",
        "name": "Johannes-Gutenberg-Schule Gernsheim",
        "loc": "Gernsheim",
        "om_id": 1809
    },
    {
        "$comment": "New Feed for Leibniz Schule for caterer WISAG",
        "provider": "mensadigital.de",
        "p": "WI2372",
        "e": "Leibniz",
        "name": "Leibnizschule Wiesbaden",
        "loc": "Wiesbaden",
        "om_id": 1836
    },
    {
        "$comment": "New Feed for Oranienschule, Caterer WISAG.",
        "provider": "mensadigital.de",
        "p": "WI2372",
        "e": "Oranien",
        "name": "Oranienschule Wiesbaden",
        "loc": "Wiesbaden",
        "om_id": 1837
    },
    {
        "provider": "mensadigital.de",
        "p": "EN2322",
        "e": "GySue",
        "name": "Gymnasium Süderelbe",
        "loc": "Hamburg",
        "om_id": 1812
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "frid",
        "name": "Gymnasium Fridericianum",
        "loc": "Erlangen",
        "om_id": 1813
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "msf",
        "name": "Grund- und Mittelschule Feucht / Kinderhort St. Jakob",
        "loc": "Feucht",
        "om_id": 1814
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "feu",
        "name": "Realschule Feucht",
        "loc": "Feucht",
        "om_id": 1815
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "SLM",
        "name": "Mittelschule St. Leonhard Nürnberg",
        "loc": "Nürnberg",
        "om_id": 1816
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "gpa",
        "name": "Georg-Paul-Amberger Grundschule",
        "loc": "Nürnberg",
        "om_id": 1817
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "Schulhaus",
        "name": "Evangelisches Montessori Kinderhaus Röttenbach",
        "loc": "Röttenbach",
        "om_id": 1818
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "ggo",
        "name": "Grundschule Großgründlach",
        "loc": "Nürnberg",
        "om_id": 1819
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "sjw",
        "name": "Kinderhaus St. Josef",
        "loc": "Weisendorf",
        "om_id": 1820
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "drb",
        "name": "Dientzenhofer-Realschule Brannenburg",
        "loc": "Brannenburg",
        "om_id": 1821
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "gsr",
        "name": "Graf-Stauffenberg-Realschule Bamberg",
        "loc": "Bamberg",
        "om_id": 1822
    },
    {
        "provider": "mensaaktiv.de",
        "p": "FO111",
        "e": "kat",
        "name": "Grund- und Mittelschule Katzwang",
        "loc": "Nürnberg",
        "om_id": 1823
    },
    {
        "provider": "mensapoint.de",
        "p": "GOE444",
        "e": "BBS",
        "name": "Berufsbildende Schule Osterode",
        "loc": "Osterode am Harz",
        "om_id": 1825
    },
    {
        "provider": "mensapoint.de",
        "p": "GOE444",
        "e": "TRG",
        "name": "Tilman-Riemenschneider-Gymnasium Osterode",
        "loc": "Osterode am Harz",
        "om_id": 1826
    },
    {
        "provider": "mensapoint.de",
        "p": "FL111",
        "e": "Ramsharde",
        "name": "Grundschule Ramsharde",
        "loc": "Flensburg",
        "om_id": 1827
    },
    {
        "provider": "mensaonline.de",
        "p": "AZ000",
        "e": "OHS",
        "name": "Otto-Hahn-Schule Westhofen",
        "loc": "Westhofen",
        "om_id": 1830
    },
    {
        "$comment": "https://max-emden.de",
        "provider": "mensalokal.de",
        "p": "EMD999",
        "e": "MAX",
        "name": "Max-Windmüller-Gymnasium Emden",
        "loc": "Emden",
        "om_id": 1848
    },
    {
        "$comment": "https://www.michael-bauer-schule.de/unsere-schule/schulkueche.html",
        "provider": "mensaonline.de",
        "p": "S243",
        "e": "MBS",
        "name": "Michael-Bauer-Schule",
        "loc": "Stuttgart",
        "om_id": 1831
    },
    {
        "provider": "mensaonline.de",
        "p": "FN222",
        "e": "RS",
        "name": "Mensa Schulzentrum Manzenberg",
        "loc": "Tettnang",
        "om_id": 1832
    },
    {
        "provider": "mensaonline.de",
        "p": "FN222",
        "e": "MGTT",
        "name": "Montfort-Gymnasium Tettnang",
        "loc": "Tettnang",
        "om_id": 1833
    },
    {
        "provider": "mensaweb.de",
        "p": "Brilon",
        "e": "H-L-S",
        "name": "Heinrich-Lübke-Schule Brilon",
        "loc": "Brilon",
        "om_id": 1834
    },
    {
        "$comment": "https://www.petrinum-brilon.de/schulleben/mensa/",
        "provider": "mensaweb.de",
        "p": "Brilon",
        "e": "Petrinum",
        "name": "Gymnasium Petrinum",
        "loc": "Brilon",
        "om_id": 1849
    },
    {
        "$comment": "https://www.gymnasium-wentorf.de/service/cafeteria.html",
        "provider": "mensaland.de",
        "p": "RZ222",
        "e": "CGW",
        "name": "Cafeteria des Gymnasiums Wentorf e.V.",
        "loc": "Wentorf bei Hamburg",
        "om_id": 1847
    },
    {
        "provider": "mensaland.de",
        "p": "LOE111",
        "e": "FWS",
        "name": "Freie Waldorfschule Lörrach",
        "loc": "Lörrach",
        "om_id": 1835
    },
    {
        "$comment": "https://www.umkirch.de/Kinder-Jugend-Senioren/Kinderbildungszentrum-KiZ/Grundschule-Uebersicht",
        "provider": "mensaland.de",
        "name": "Grundschule Umkirch",
        "loc": "Umkirch",
        "p": "FR333",
        "e": "GS",
        "om_id": 1851
    },
    {
        "$comment": "https://euregio-gymnasium.bocholt.de/formulare-service/",
        "provider": "mensahaus.de",
        "p": "BOR2587",
        "e": "Euregio",
        "name": "Euregio-Gymnasium",
        "loc": "Bocholt",
        "om_id": 1846
    },
    {
        "$comment": "https://www.werkgymnasium.de/schule/mensa/",
        "provider": "mensaweb.de",
        "p": "HDH111",
        "e": "WG",
        "name": "Werkgymnasium",
        "loc": "Heidenheim",
        "om_id": 1850
    },
    {
        "$comment": "https://www.als-kusterdingen.de/unsere-schule/betreuung/",
        "provider": "mensaservice.de",
        "p": "TUE124",
        "e": "ALS",
        "name": "Astrid-Lindgren-Schule",
        "loc": "Kusterdingen",
        "om_id": 1856
    },
    {
        "$comment": "https://www.rohraeckerschulzentrum.de/aktuelles",
        "provider": "mensaservice.de",
        "p": "ES222",
        "e": "Sprache",
        "name": "Rohräckerschulzentrum",
        "loc": "Esslingen",
        "om_id": 1862
    },
    {
        "$comment": "https://www.richtsbergschule.de/mittagessen/",
        "provider": "mensahaus.de",
        "p": "MR2468",
        "e": "RGS",
        "name": "Richtsberg-Gesamtschule",
        "loc": "Marburg",
        "om_id": 1858
    },
    {
        "$comment": "https://www.gesamtschule-stade.de/?page_id=1330",
        "provider": "mensaland.de",
        "p": "CUX124",
        "e": "IGS-Stade",
        "name": "Intgrierte Gesamtschule Stade",
        "loc": "Stade",
        "om_id": 1871
    },
    {
        "$comment": "https://www.richard-linde-weg.de/unterricht/ganztagsschule/schulmensa.html",
        "provider": "mensaland.de",
        "p": "HH666",
        "e": "RLW",
        "name": "STS Richard-Linde-Weg",
        "loc": "Hamburg",
        "om_id": 1876
    },
    {
        "$comment": "https://www.kleineburg.de",
        "provider": "mensawelten.de",
        "p": "BS111",
        "e": "KB",
        "name": "Gymnasium Kleine Burg",
        "loc": "Braunschweig",
        "om_id": 1854
    },
    {
        "$comment": "https://www.schuleambotanischengarten.de/mittagessen-mensamax/",
        "provider": "mensawelten.de",
        "p": "GOE197",
        "e": "SaBG",
        "name": "Schule am Botanischen Garten",
        "loc": "Hann. Münden",
